unique_name: ProductsDS
object_type: dataset
label: ProductsDS
columns:
  - name: productid
    data_type: int
  - name: name
    data_type: string
  - name: productnumber
    data_type: string
  - name: productsubcategoryid
    data_type: int
  - name: color
    data_type: string
  - name: size
    data_type: string
  - name: stocklevel
    data_type: int
  - name: supplier
    data_type: string
connection_id: con_postgres_public_v2
table: productsview
