unique_name: ProductSubcategoriesDS
object_type: dataset
label: ProductSubcategoriesDS
columns:
  - name: productsubcategoryid
    data_type: int
  - name: productcategoryid
    data_type: int
  - name: productsubcategoryname
    data_type: string
connection_id: con_postgres_public_v2
table: productsubcategoriesview
